#!/bin/sh

if [ -d './secret' ]; then
  echo "ERROR: 'secret' directory already exists"
  exit 255
fi

mkdir -p ./secret/wagri_api_client_id
echo "Add CLIENT_ID here" > ./secret/wagri_api_client_id/wagri_api_client_id

mkdir -p ./secret/wagri_api_client_secret
echo "Add CLIENT_SECRET here" > ./secret/wagri_api_client_secret/wagri_api_client_secret

mkdir -p ./secret/wagri_api_vendor_id
echo "Add VENDOR_ID here" > ./secret/wagri_api_vendor_id/wagri_api_vendor_id

mkdir -p ./secret/auth
echo '''{
  "udonko": "udonko"
}''' > ./secret/auth/auth
