env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
  - eslint:recommended
overrides:
  - files:
      - '**/*.test.js'
    env:
      jest: true

parserOptions:
  ecmaVersion: latest
rules: {}
